-- 教育管家｜第一版 Master Seed
-- 不包含真实家庭、学生或财务数据

insert into subject_master
(education_level,subject_code,subject_name,subject_group,curriculum_pathway,level_code,sort_order)
values
('primary','P-ENG','English','语言','Primary','P1-P6',10),
('primary','P-MT','Mother Tongue','语言','Primary','P1-P6',20),
('primary','P-MATH','Mathematics','数学','Primary','P1-P6',30),
('primary','P-SCI','Science','科学','Primary','P3-P6',40),
('primary','P-ART','Art','艺术','Primary','P1-P6',50),
('primary','P-MUSIC','Music','艺术','Primary','P1-P6',60),
('primary','P-PE','Physical Education','体育','Primary','P1-P6',70),
('primary','P-CCE','Character and Citizenship Education','品格与公民教育','Primary','P1-P6',80),
('secondary','SEC-ENG','English','语言','Secondary','S1-S4',10),
('secondary','SEC-MT','Mother Tongue','语言','Secondary','S1-S4',20),
('secondary','SEC-MATH','Mathematics','数学','Secondary','S1-S4',30),
('secondary','SEC-AMATH','Additional Mathematics','数学','Secondary','S1-S4',35),
('secondary','SEC-SCI','Science','科学','Secondary','S1-S4',40),
('secondary','SEC-HUM','Humanities','人文','Secondary','S1-S4',50),
('secondary','SEC-ART','Art','艺术','Secondary','S1-S4',60),
('secondary','SEC-DNT','Design & Technology','设计与工艺','Secondary','S1-S4',70),
('secondary','SEC-FCE','Food & Consumer Education','食品与消费者教育','Secondary','S1-S4',80),
('secondary','SEC-COMPUTING','Computing','计算机','Secondary','S1-S4',90),
('secondary','SEC-ELECTIVE','Elective / Combined Subject','选修 / 组合科目','Secondary','S3-S4',100),
('jc','JC-GP','General Paper','核心','JC','H1/H2',10),
('jc','JC-PW','Project Work','核心','JC','H1/H2',20),
('jc','JC-MT','Mother Tongue','语言','JC','H1',30),
('jc','JC-CLL','Chinese Language & Literature','语言与文学','JC','H1/H2',40),
('jc','JC-MLL','Malay Language & Literature','语言与文学','JC','H1/H2',50),
('jc','JC-TLL','Tamil Language & Literature','语言与文学','JC','H1/H2',60),
('jc','JC-ELL','English Language & Linguistics','语言','JC','H1/H2',70),
('jc','JC-MATH','Mathematics','数学','JC','H1/H2',80),
('jc','JC-FMATH','Further Mathematics','数学','JC','H2',90),
('jc','JC-BIO','Biology','科学','JC','H1/H2',100),
('jc','JC-CHEM','Chemistry','科学','JC','H1/H2',110),
('jc','JC-PHYS','Physics','科学','JC','H1/H2',120),
('jc','JC-COMP','Computing','计算机','JC','H1/H2',130),
('jc','JC-ECON','Economics','人文商科','JC','H1/H2',140),
('jc','JC-GEO','Geography','人文','JC','H1/H2',150),
('jc','JC-HIST','History','人文','JC','H1/H2',160),
('jc','JC-LIT','Literature in English','文学','JC','H1/H2',170),
('jc','JC-CHINA','China Studies','人文','JC','H1/H2',180),
('jc','JC-ART','Art','艺术','JC','H1/H2',190),
('jc','JC-MUSIC','Music','艺术','JC','H1/H2',200),
('jc','JC-TSD','Theatre Studies & Drama','艺术','JC','H1/H2',210),
('jc','JC-POA','Principles of Accounting','商科','JC','H1/H2',220),
('jc','JC-MOB','Management of Business','商科','JC','H1/H2',230)
on conflict (education_level,subject_code) do update set
subject_name=excluded.subject_name,
subject_group=excluded.subject_group,
curriculum_pathway=excluded.curriculum_pathway,
level_code=excluded.level_code,
sort_order=excluded.sort_order,
is_active=true;
